import type { Metadata } from "next";
import "./globals.css";

import ClientSessionProvider from "@/components/ClientSessionProvider"
import { OrderProvider } from "@/components/OrderProvider"
import TitleTestNav from "@/components/titleComponent/TitleTestNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientSessionProvider>
        <OrderProvider>
          <body>
            <main className="bg-amber-50 text-black min-h-screen">
              <TitleTestNav />
              {children}
            </main>
          </body>
        </OrderProvider>
      </ClientSessionProvider>
    </html>
  );
}
