import type { Metadata } from "next";
import "./globals.css";

import TitleTestNav from "@/components/titleComponent/TitleTestNav";
import ClientSessionProvider from "@/components/ClientSessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientSessionProvider>
        <body>
          <main className="bg-amber-50 text-black min-h-screen">
            <TitleTestNav />
            {children}
          </main>
        </body>
      </ClientSessionProvider>
    </html>
  );
}
